name: ${project.name}
version: ${project.version}
author: ${project.organization.name}
main: ${project.main}
api-version: 1.13

commands:
  emote:
    description: Use /emote to see all commands
    usage: /emote <arguments>
    aliases:
      - emotes
      - emotenpc
      - enpc